export type Golfer = {
  id: string;
  espnId: string;
  name: string;
  salary: number;
};

// Texas Children's Houston Open — DraftKings salaries
export const GOLFERS: Golfer[] = [
  { id: "minwoolee",      espnId: "4410932",  name: "Min Woo Lee",                    salary: 9900  },
  { id: "gotterup",       espnId: "4690755",  name: "Chris Gotterup",                 salary: 9800  },
  { id: "burns",          espnId: "9938",     name: "Sam Burns",                      salary: 9700  },
  { id: "koepka",         espnId: "6798",     name: "Brooks Koepka",                  salary: 9600  },
  { id: "knapp",          espnId: "9843",     name: "Jake Knapp",                     salary: 9500  },
  { id: "fowler",         espnId: "3702",     name: "Rickie Fowler",                  salary: 9400  },
  { id: "kitayama",       espnId: "10364",    name: "Kurt Kitayama",                  salary: 9300  },
  { id: "nhoejgaard",     espnId: "11250",    name: "Nicolai Højgaard",               salary: 9200  },
  { id: "penge",          espnId: "4585549",  name: "Marco Penge",                    salary: 9100  },
  { id: "scott",          espnId: "388",      name: "Adam Scott",                     salary: 9000  },
  { id: "english",        espnId: "5408",     name: "Harris English",                 salary: 8900  },
  { id: "griffin",        espnId: "4404992",  name: "Ben Griffin",                    salary: 8800  },
  { id: "lowry",          espnId: "4587",     name: "Shane Lowry",                    salary: 8700  },
  { id: "thorbjornsen",   espnId: "4425904",  name: "Michael Thorbjornsen",           salary: 8600  },
  { id: "hall",           espnId: "4589438",  name: "Harry Hall",                     salary: 8500  },
  { id: "rgerard",        espnId: "5076021",  name: "Ryan Gerard",                    salary: 8400  },
  { id: "clark",          espnId: "11119",    name: "Wyndham Clark",                  salary: 8300  },
  { id: "mitchell",       espnId: "8906",     name: "Keith Mitchell",                 salary: 8200  },
  { id: "rhoejgaard",     espnId: "11253",    name: "Rasmus Højgaard",                salary: 8100  },
  { id: "day",            espnId: "1680",     name: "Jason Day",                      salary: 8000  },
  { id: "coody",          espnId: "4837368",  name: "Pierceson Coody",                salary: 8000  },
  { id: "samstevens",     espnId: "4426181",  name: "Sam Stevens",                    salary: 7900  },
  { id: "pendrith",       espnId: "9658",     name: "Taylor Pendrith",                salary: 7900  },
  { id: "smalley",        espnId: "9484",     name: "Alex Smalley",                   salary: 7800  },
  { id: "jaeger",         espnId: "6937",     name: "Stephan Jaeger",                 salary: 7800  },
  { id: "raiaaaron",      espnId: "10906",    name: "Aaron Rai",                      salary: 7700  },
  { id: "zalatoris",      espnId: "9877",     name: "Will Zalatoris",                 salary: 7700  },
  { id: "theegala",       espnId: "10980",    name: "Sahith Theegala",                salary: 7600  },
  { id: "finau",          espnId: "2230",     name: "Tony Finau",                     salary: 7600  },
  { id: "rodgers",        espnId: "6825",     name: "Patrick Rodgers",                salary: 7600  },
  { id: "im",             espnId: "11382",    name: "Sungjae Im",                     salary: 7500  },
  { id: "thompson",       espnId: "4602218",  name: "Davis Thompson",                 salary: 7500  },
  { id: "castillo",       espnId: "4691931",  name: "Ricky Castillo",                 salary: 7500  },
  { id: "greyserman",     espnId: "11101",    name: "Max Greyserman",                 salary: 7400  },
  { id: "jordan",         espnId: "9506",     name: "Jordan Smith",                   salary: 7400  },
  { id: "fox",            espnId: "4251",     name: "Ryan Fox",                       salary: 7400  },
  { id: "woodland",       espnId: "3550",     name: "Gary Woodland",                  salary: 7400  },
  { id: "reitan",         espnId: "4348470",  name: "Kristoffer Reitan",              salary: 7300  },
  { id: "richoe",         espnId: "11385",    name: "Rico Hoey",                      salary: 7300  },
  { id: "haotong",        espnId: "9221",     name: "Haotong Li",                     salary: 7300  },
  { id: "echavarria",     espnId: "4408316",  name: "Nico Echavarria",                salary: 7300  },
  { id: "poston",         espnId: "10505",    name: "J.T. Poston",                    salary: 7300  },
  { id: "olesen",         espnId: "5140",     name: "Thorbjørn Olesen",               salary: 7200  },
  { id: "potgieter",      espnId: "5080439",  name: "Aldrich Potgieter",              salary: 7200  },
  { id: "brennan",        espnId: "4921329",  name: "Michael Brennan",                salary: 7200  },
  { id: "yellamaraju",    espnId: "5143175",  name: "Sudarshan Yellamaraju",          salary: 7200  },
  { id: "ghim",           espnId: "11456",    name: "Doug Ghim",                      salary: 7200  },
  { id: "bezuidenhout",   espnId: "9243",     name: "Christiaan Bezuidenhout",        salary: 7100  },
  { id: "dumont",         espnId: "5076011",  name: "Adrien Dumont de Chassart",      salary: 7100  },
  { id: "hughes",         espnId: "6931",     name: "Mackenzie Hughes",               salary: 7100  },
  { id: "kimtom",         espnId: "4602673",  name: "Tom Kim",                        salary: 7100  },
  { id: "schmid",         espnId: "4566443",  name: "Matti Schmid",                   salary: 7100  },
  { id: "power",          espnId: "6001",     name: "Séamus Power",                   salary: 7100  },
  { id: "hodges",         espnId: "4404991",  name: "Lee Hodges",                     salary: 7000  },
  { id: "neergaard",      espnId: "4858859",  name: "Rasmus Neergaard-Petersen",      salary: 7000  },
  { id: "cole",           espnId: "10522",    name: "Eric Cole",                      salary: 7000  },
  { id: "meissner",       espnId: "4791222",  name: "Mac Meissner",                   salary: 7000  },
  { id: "mccarthy",       espnId: "10054",    name: "Denny McCarthy",                 salary: 7000  },
  { id: "parry",          espnId: "4671",     name: "John Parry",                     salary: 7000  },
  { id: "ventura",        espnId: "4351896",  name: "Kris Ventura",                   salary: 7000  },
  { id: "Wallace",        espnId: "10548",    name: "Matt Wallace",                   salary: 6900  },
  { id: "mcgreevy",       espnId: "11383",    name: "Max McGreevy",                   salary: 6900  },
  { id: "mouw",           espnId: "5076025",  name: "William Mouw",                   salary: 6900  },
  { id: "kimsh",          espnId: "4698579",  name: "S.H. Kim",                       salary: 6900  },
  { id: "kroy",           espnId: "4408320",  name: "Kevin Roy",                      salary: 6900  },
  { id: "swensson",       espnId: "4699329",  name: "Jesper Svensson",                salary: 6800  },
  { id: "horschel",       espnId: "1651",     name: "Billy Horschel",                 salary: 6800  },
  { id: "kirkchris",      espnId: "3449",     name: "Chris Kirk",                     salary: 6800  },
  { id: "grillo",         espnId: "5882",     name: "Emiliano Grillo",                salary: 6800  },
  { id: "blanchet",       espnId: "4618114",  name: "Chandler Blanchet",              salary: 6800  },
  { id: "lipsky",         espnId: "6701",     name: "David Lipsky",                   salary: 6800  },
  { id: "yu",             espnId: "4349547",  name: "Kevin Yu",                       salary: 6700  },
  { id: "ramey",          espnId: "10057",    name: "Chad Ramey",                     salary: 6700  },
  { id: "browndan",       espnId: "1407",     name: "Dan Brown",                      salary: 6700  },
  { id: "ford",           espnId: "5150294",  name: "David Ford",                     salary: 6700  },
  { id: "vwhaley",        espnId: "4408315",  name: "Vince Whaley",                   salary: 6700  },
  { id: "keefer",         espnId: "5217048",  name: "Johnny Keefer",                  salary: 6700  },
  { id: "eckroat",        espnId: "4425898",  name: "Austin Eckroat",                 salary: 6700  },
  { id: "putnam",         espnId: "5502",     name: "Andrew Putnam",                  salary: 6700  },
  { id: "tosti",          espnId: "4358081",  name: "Alejandro Tosti",                salary: 6600  },
  { id: "stevensfisk",    espnId: "4426182",  name: "Steven Fisk",                    salary: 6600  },
  { id: "higgo",          espnId: "11393",    name: "Garrick Higgo",                  salary: 6600  },
  { id: "dou",            espnId: "8889",     name: "Zecheng Dou",                    salary: 6600  },
  { id: "pavon",          espnId: "10596",    name: "Matthieu Pavon",                 salary: 6600  },
  { id: "ewart",          espnId: "5075652",  name: "A.J. Ewart",                     salary: 6600  },
  { id: "wu",             espnId: "4423323",  name: "Dylan Wu",                       salary: 6600  },
  { id: "hossler",        espnId: "6011",     name: "Beau Hossler",                   salary: 6500  },
  { id: "glover",         espnId: "676",      name: "Lucas Glover",                   salary: 6500  },
  { id: "hoge",           espnId: "6086",     name: "Tom Hoge",                       salary: 6500  },
  { id: "bauchou",        espnId: "10030",    name: "Zach Bauchou",                   salary: 6500  },
  { id: "clanton",        espnId: "5215039",  name: "Luke Clanton",                   salary: 6500  },
  { id: "salinda",        espnId: "4589406",  name: "Isaiah Salinda",                 salary: 6500  },
  { id: "kanaya",         espnId: "4410612",  name: "Takumi Kanaya",                  salary: 6500  },
  { id: "vegas",          espnId: "1030",     name: "Jhonattan Vegas",                salary: 6400  },
  { id: "saddier",        espnId: "6962",     name: "Adrien Saddier",                 salary: 6400  },
  { id: "sargent",        espnId: "5139663",  name: "Gordon Sargent",                 salary: 6400  },
  { id: "hubbard",        espnId: "9143",     name: "Mark Hubbard",                   salary: 6400  },
  { id: "phillips",       espnId: "4587989",  name: "Chandler Phillips",              salary: 6400  },
  { id: "riley",          espnId: "10058",    name: "Davis Riley",                    salary: 6400  },
  { id: "svensson",       espnId: "9127",     name: "Adam Svensson",                  salary: 6400  },
  { id: "ryansam",        espnId: "7001",     name: "Sam Ryder",                      salary: 6400  },
  { id: "fishburn",       espnId: "4358083",  name: "Patrick Fishburn",               salary: 6300  },
  { id: "lamprecht",      espnId: "11395",    name: "Christo Lamprecht",              salary: 6300  },
  { id: "howell",         espnId: "5289811",  name: "Mason Howell",                   salary: 6300  },
  { id: "shipley",        espnId: "5209442",  name: "Neal Shipley",                   salary: 6300  },
  { id: "jvanderlaan",    espnId: "4361934",  name: "John VanDerLaan",                salary: 6300  },
  { id: "dwalker",        espnId: "4408319",  name: "Danny Walker",                   salary: 6300  },
  { id: "lebioda",        espnId: "11387",    name: "Hank Lebioda",                   salary: 6300  },
  { id: "stanger",        espnId: "10990",    name: "Jimmy Stanger",                  salary: 6300  },
  { id: "suber",          espnId: "4982182",  name: "Jackson Suber",                  salary: 6300  },
  { id: "vilips",         espnId: "5147097",  name: "Karl Vilips",                    salary: 6200  },
  { id: "burgoon",        espnId: "1626",     name: "Bronson Burgoon",                salary: 6200  },
  { id: "hammer",         espnId: "10047",    name: "Cole Hammer",                    salary: 6200  },
  { id: "mullinax",       espnId: "9626",     name: "Trey Mullinax",                  salary: 6200  },
  { id: "nyholm",         espnId: "4375977",  name: "Pontus Nyholm",                  salary: 6200  },
  { id: "vanrooyen",      espnId: "9364",     name: "Erik van Rooyen",                salary: 6200  },
  { id: "hirata",         espnId: "5075548",  name: "Kensei Hirata",                  salary: 6200  },
  { id: "highsmith",      espnId: "4868733",  name: "Joe Highsmith",                  salary: 6200  },
  { id: "chatfield",      espnId: "5113338",  name: "Davis Chatfield",                salary: 6100  },
  { id: "kizzire",        espnId: "3980",     name: "Patton Kizzire",                 salary: 6100  },
  { id: "dunlap",         espnId: "4832046",  name: "Nick Dunlap",                    salary: 6100  },
  { id: "campbell",       espnId: "9525",     name: "Brian Campbell",                 salary: 6100  },
  { id: "garnett",        espnId: "2283",     name: "Brice Garnett",                  salary: 6100  },
  { id: "khlee",          espnId: "7083",     name: "K.H. Lee",                       salary: 6100  },
  { id: "malnati",        espnId: "5692",     name: "Peter Malnati",                  salary: 6100  },
  { id: "rozo",           espnId: "7120",     name: "Marcelo Rozo",                   salary: 6100  },
  { id: "cauley",         espnId: "5338",     name: "Bud Cauley",                     salary: 6900  },
  { id: "mccarty",        espnId: "4901368",  name: "Matthew McCarty",                salary: 7200  },
  { id: "willett",        espnId: "4304",     name: "Danny Willett",                  salary: 6000  },
  { id: "schenk",         espnId: "10372",    name: "Adam Schenk",                    salary: 6000  },
  { id: "jkang",          espnId: "4408318",  name: "Jeffrey Kang",                   salary: 6000  },
  { id: "russell",        espnId: "11022",    name: "Casey Russell",                  salary: 6000  },
  { id: "waring",         espnId: "3474",     name: "Paul Waring",                    salary: 6000  },
  { id: "wise",           espnId: "10577",    name: "Aaron Wise",                     salary: 6000  },
  { id: "hoffman",        espnId: "205",      name: "Charley Hoffman",                salary: 6000  },
  { id: "campos",         espnId: "3683",     name: "Rafael Campos",                  salary: 6000  },
];

export const SALARY_CAP = 50000;
export const PICK_COUNT = 6;
